#networks:
#  #spark-hive:
#    #driver: bridge
networks:
  default:
    #external: true
    name: spark-hive

volumes:
  namenode:
  datanode:
  historyserver:

services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.namenode
    # image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    container_name: namenode
    env_file:
      - ./hadoop-dsai.env
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_HOME=/opt/hadoop-3.1.3
    ports:
      - "9870:9870"    # NameNode HTTP port
      # - "9010:9000"  # HDFS port
    volumes:
      - namenode:/hadoop/dfs/name
      - ../../Hadoop/:/opt/Hadoop
      - ../../Spark/:/opt/Spark

  datanode:
    build:
      context: .
      dockerfile: Dockerfile.datanode
    # image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: datanode
    env_file:
      - ./hadoop-dsai.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HADOOP_HOME: /opt/hadoop-3.1.3
    ports:
      - "9864:9864"    # DataNode HTTP port
      # - "9010:9000"  # HDFS port
    volumes:
      - datanode:/hadoop/dfs/data
      - ../../Hadoop/:/opt/Hadoop
      - ../../Spark/:/opt/Spark

  resourcemanager:
    build:
      context: .
      dockerfile: Dockerfile.resourcemanager
    container_name: resourcemanager
    restart: always
    ports:
      - "8889:8088"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
      HADOOP_HOME: /opt/hadoop-3.1.3
    env_file:
      - ./hadoop-dsai.env

  nodemanager1:
    build:
      context: .
      dockerfile: Dockerfile.nodemanager
    container_name: nodemanager
    restart: always
    ports:
      - "8042:8042"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
      HADOOP_HOME: /opt/hadoop-3.1.3
    env_file:
      - ./hadoop-dsai.env

  historyserver:
    build:
      context: .
      dockerfile: Dockerfile.historyserver
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
      HADOOP_HOME: /opt/hadoop-3.1.3
    ports:
      - "8188:8188"
    volumes:
      - historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-dsai.env

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hive-dsai.env
    volumes:
      - ../../Hadoop/:/opt/Hadoop
      - ../../Spark/:/opt/Spark
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hive-dsai.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    container_name: presto-coordinator
    ports:
      - "8089:8089"
#Disabling - not using spark commented out to try later - if you want to 
  # spark-master:
  #   image: bitnami/spark:3.5.2
  #   container_name: spark-master
  #   depends_on:
  #     - namenode
  #     - datanode
  #   ports:
  #     - "8080:8080"  # Spark Master web UI
  #     - "7077:7077"  # Spark Master to Worker communication
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #     - SERVICE_PRECONDITION=namenode:9870 datanode:9864
  #     - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000
  #     - SPARK_HADOOP_IO_COMPRESSION_CODECS=org.apache.hadoop.io.compress.SnappyCodec

  # spark-worker-1:
  #   image: bitnami/spark:3.5.2
  #   container_name: spark-worker-1
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8081:8081"  # Spark Worker web UI
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #     - SPARK_WORKER_MEMORY=2G
  #     - SPARK_WORKER_CORES=2
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #     - SERVICE_PRECONDITION=spark-master:7077
  #     - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000
  #     - SPARK_HADOOP_IO_COMPRESSION_CODECS=org.apache.hadoop.io.compress.SnappyCodec
